name: Remove artifacts

on:
  schedule:
    # Every day at 19.02 GMT +2
    - cron: '04 17 * * *'
jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1.2.0
      with:
        age: '2 days'
        # Optional inputs
        skip-tags: true
        skip-recent: 7
