name: Remove old artifacts

on:
  schedule:
    # Every other day at 03.15 GMT +2
    - cron: '15 01 */2 * *'
jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1.2.0
      with:
        age: '2 hours'
        # Optional inputs
        skip-tags: true
        skip-recent: 3
