name: Remove artifacts

on:
  push:
    branches:
      - master
  schedule:
    # Every day at 05.15 GMT +2
    - cron: '15 03 * * *'
jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1.2.0
      with:
        age: '2 days'
        # Optional inputs
        skip-tags: true
        skip-recent: 18
